---
title: "ETRmax TPC analysis"
author: "Christine"
date: "2023-10-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Documents/PhD/Chapter 3/Data/Phenoplate data/R analysis")
setwd("~/Documents/PhD/Chapter 3/Data/Phenoplate data/R analysis")

ETRmax_data <- read.csv("3. Thermal Curves/outputs/ETR_max/ed50.csv")
# Filter outliers over 40 (4 removed)
ETRmax_data <- filter(ETRmax_data, ed50 < 40)

#make Group a factor
ETRmax_data$Group = as.factor(ETRmax_data$Group)
```

#Check normality of ED50 values and run test
```{r}
#density plot to view distribution
plot(density(ETRmax_data$ed50))

#ETRmax_data$ed50_log <- log(ETRmax_data$ed50)
shapiro.test(ETRmax_data$ed50) #did not pass
bartlett.test(ed50 ~ Group, data = ETRmax_data) #did not pass

#non-parametric alternative
kruskal.test(ed50 ~ Group, data = ETRmax_data)

Dunn_result <- dunnTest(ed50 ~ Group, data = ETRmax_data, method="bh")
View(Dunn_result$res)
write.csv(Dunn_result$res, "Parameter stats analysis/ED50_posthoc_results.csv")

```

#plot
```{r}
library(ggplot2)
source("utils/default_theme.r")

#aggregate data + create StdErr function
stdErr <- function(x) sd(x)/sqrt(length(x))
stdErrs = aggregate(ETRmax_data$ed50, by=list(ETRmax_data$Group), stdErr)
means = aggregate(ETRmax_data$ed50, by=list(ETRmax_data$Group), mean)
aggregated <- data.frame(Group=means[1], Mean=means$x, StdErr=stdErrs$x)
colnames(aggregated) = c( "Group" , "Mean", "StdErr" )


ETRmax_ED50_plot = ggplot(data=aggregated, aes(x=Group, y=Mean)) +
  geom_point(stat="identity", position=position_dodge(width=1), size=2) +
  geom_errorbar(aes(ymin=Mean-StdErr, ymax=Mean+StdErr), width=.05, size=0.4,colour="azure4",
                 position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1,)) + 
    theme(axis.title.x = element_text(margin = margin(t = 10))) +
    theme(axis.title.y = element_text(margin = margin(r = 10))) +
  scale_y_continuous(breaks = c(35,36,37), limits = c(35, 37)) +
  # ylim(35,37) +
  ylab ("Mean Ed50 (±SE)") +
  xlab ("Group") +
  default_theme
  
print(ETRmax_ED50_plot)
ggsave("Parameter stats analysis/ETRmax_ED50_plot.png")


```


```{r}
library(drc)
library(ggplot2)
library(readr)

input <- "2. Rapid Light Curves/outputs/rlc_etr_metrics_eilers.csv"
plots <- "Parameter stats analysis/"

# Load Data
data <- read_csv(input)

# Fit DRM (4-parameter log-logistic model)
model <-  drm(ETR_max ~ Temperature,
    data = mean_by_group, curveid = Group,
    fct = LL.3(names = c("hill", "max", "ed50"))
)

# Summary of the model
summary(model)

#Outputs ED50 values for each group
compParm(DRCpam, "ed50")
compParm(DRCpam, "ed50", "-")
ED(DRCpam, c(50))[, 1]

# Generate Temperature values for prediction
Temperature_values <- seq(min(data$Temperature), max(data$Temperature), length.out = 100)

# Create an empty list to store data frames for each group
plot_data_list <- list()

# Loop through each Group level and create data frames
for (i in 1:length(unique(data$Group))) {
  group_level <- unique(data$Group)[i]
  
  # Subset data for the current group
  group_data <- subset(data, Group == group_level)
  
  # Predict responses for the current group
  predicted_responses <- predict(model, newdata = data.frame(Temperature = Temperature_values, Group = group_level))
  
  # Create data frame for the current group
  group_plot_data <- data.frame(Temperature = Temperature_values,
                                response = predicted_responses,
                                Group = factor(group_level, levels = unique(data$Group)))
  
  # Append the data frame to the list
  plot_data_list[[i]] <- group_plot_data
}

# Combine data frames from the list into one data frame
plot_data <- do.call(rbind, plot_data_list)

# Create ggplot with separate lines for each Group
ggplot(data = plot_data, aes(x = Temperature, y = response, color = Group)) +
  geom_line() +
  #geom_point(data = data, aes(x = Temperature, y = ETR_max, color = Group), size = 3, alpha = 0.7) +
  labs(x = "Temperature", y = "ETRmax") +
  ggtitle("ED50 curve") +
  default_theme

ggsave(paste0(plots,"ETRmax group averages.png"))

```
