fluorcam_data from parse_flurcam_files.rmd and creates a data frame with cols: 
SampleName, Well, Reef, Site, Habitat, Pale, Group, Temperature, PAR, ETR, QY

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Documents/PhD/Chapter 4/Data/Phenoplate data/R analysis")

fluorcam_data <- "fluorcam_data.csv"
output <- "Rapid Light Curves/fluorcam_RLC_data.csv"
```

```{r}
fluorcam_data <- read.csv(fluorcam_data)

etr_data <- NULL
for (i in seq_len(nrow(fluorcam_data))) {
    sample <- fluorcam_data[i, ]
    for (m in seq(1:15)) {
        new_row <- data.frame(
            SampleID = sample$SampleID,
            Area = sample$Area,
            # @todo make more generic
            Reef = as.character(sample$Reef),
            Site = as.character(sample$Site),
            Habitat = as.character(sample$Habitat),
            HealthScore = as.character(sample$HealthScore),
            Group = as.character(sample$Group),
            Temperature = sample$Temperature,
            PAR = fluorcam_data[i, paste0("T2_PAR", m)],
            ETR = fluorcam_data[i, paste0("T2_ETR", m)],
            QY = fluorcam_data[i, paste0("T2_QY_Lss", m)]
        )
        etr_data <- rbind(etr_data, new_row)
    }
}

write.csv(etr_data, output)
```

