---
title: "QYek stats analysis"
author: "Christine"
date: "2023-06-14"
output: html_document
---

```{r}
library(dplyr)

setwd("~/Documents/PhD/Chapter 3/Data/Phenoplate data/R analysis")
QY_parameters <- read.csv("Thermal Curves/QY_ek/inverted exponential.csv", header = TRUE, stringsAsFactors = TRUE)
# Only the cols we care about
QY_parameters <- QY_parameters[, c(2, 3, 4, 5, 6)]
# Rename cols to simplify
colnames(QY_parameters) <- c('Sample', 'SampleGroup', 'S', 'k', 'I')
```

#test & assumptions S
```{r}
anova_S <- aov(S ~ SampleGroup, data = QY_parameters)
summary(anova_S)
TukeyHSD(anova_S)
#boxplot(S ~ SampleGroup, data = QY_parameters)

#Normality test
shapiro.test(QY_parameters$S)

#Histogram
hist(QY_parameters$S, col='steelblue')

```

#test & assumptions k
```{r}
anova_k <- aov(k ~ SampleGroup, data = QY_parameters)
summary(anova_k)
TukeyHSD(anova_k)
#boxplot(k ~ SampleGroup, data = QY_parameters)

#Normality test
shapiro.test(QY_parameters$k)

#Histogram
hist(QY_parameters$k, col='steelblue')
```

# Boxplots
```{r}
library(ggplot2)

ggplot(QY_parameters, aes(SampleGroup, S)) +
  geom_boxplot() +
  theme(axis.text.x=element_text(angle = 45, hjust = 1)) +
  christineTheme 

ggplot(QY_parameters, aes(SampleGroup, k)) +
  geom_boxplot() +
  theme(axis.text.x=element_text(angle = 45, hjust = 1)) +
  christineTheme
```